// SnapshotHelper.swift
// https://github.com/fastlane/fastlane/blob/master/snapshot/lib/assets/SnapshotHelper.swift
//
// This file is generated by fastlane snapshot and must be included in the
// UI test target so that the snapshot() function is available in test code.

import Foundation
import XCTest

var deviceLanguage = ""
var locale = ""

func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
    Snapshot.setupSnapshot(app, waitForAnimations: waitForAnimations)
}

func snapshot(_ name: String, waitForLoadingIndicator: Bool) {
    if waitForLoadingIndicator {
        Snapshot.snapshot(name)
    } else {
        Snapshot.snapshot(name, timeWaitingForIdle: 0)
    }
}

func snapshot(_ name: String, timeWaitingForIdle timeout: TimeInterval = 20) {
    Snapshot.snapshot(name, timeWaitingForIdle: timeout)
}

enum SnapshotError: Error, CustomDebugStringConvertible {
    case cannotDetectUser
    case cannotFindHomeDirectory
    case cannotFindSimulatorHomeDirectory
    case cannotAccessSimulatorHomeDirectory(String)

    var debugDescription: String {
        switch self {
        case .cannotDetectUser:
            return "Couldn't find the current user 😣"
        case .cannotFindHomeDirectory:
            return "Couldn't find the home directory 😕"
        case .cannotFindSimulatorHomeDirectory:
            return "Couldn't find the simulator home directory. Please ensure you're running in a simulator."
        case .cannotAccessSimulatorHomeDirectory(let path):
            return "Can't access the simulator home directory: \(path)"
        }
    }
}

@objcMembers
open class Snapshot: NSObject {
    static var app: XCUIApplication?
    static var waitForAnimations: Bool = true
    static var cacheDirectory: URL?
    static var screenshotsDirectory: URL? {
        return cacheDirectory?.appendingPathComponent("screenshots", isDirectory: true)
    }

    open class func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
        Snapshot.app = app
        Snapshot.waitForAnimations = waitForAnimations

        do {
            let cacheDir = try cacheDirectoryURL()
            Snapshot.cacheDirectory = cacheDir
            setLanguage(app)
            setLocale(app)
            setLaunchArguments(app)
        } catch let error {
            print("Problem setting up snapshot: \(error)")
        }
    }

    class func setLanguage(_ app: XCUIApplication) {
        guard let cacheDirectory = Snapshot.cacheDirectory else { return }
        let path = cacheDirectory.appendingPathComponent("language.txt")
        if let data = try? Data(contentsOf: path),
           let lang = String(data: data, encoding: .utf8) {
            deviceLanguage = lang
            app.launchArguments += ["-AppleLanguages", "(\(lang))"]
        }
    }

    class func setLocale(_ app: XCUIApplication) {
        guard let cacheDirectory = Snapshot.cacheDirectory else { return }
        let path = cacheDirectory.appendingPathComponent("locale.txt")
        if let data = try? Data(contentsOf: path),
           let loc = String(data: data, encoding: .utf8) {
            locale = loc
            app.launchArguments += ["-AppleLocale", "\"\(loc)\""]
        }
    }

    class func setLaunchArguments(_ app: XCUIApplication) {
        guard let cacheDirectory = Snapshot.cacheDirectory else { return }
        let path = cacheDirectory.appendingPathComponent("snapshot-launch_arguments.txt")
        guard let data = try? Data(contentsOf: path),
              let args = String(data: data, encoding: .utf8) else { return }
        app.launchArguments += args.components(separatedBy: "\n")
    }

    open class func snapshot(_ name: String, timeWaitingForIdle timeout: TimeInterval = 20) {
        if timeout > 0 {
            waitForLoadingIndicatorToDisappear(within: timeout)
        }

        print("snapshot: \(name)") // Used by fastlane to find the screenshot

        if Snapshot.waitForAnimations {
            sleep(1)
        }

        #if os(OSX)
            XCUIApplication().typeKey(XCUIKeyboardKeySecondaryFn, modifierFlags: [])
        #else
            let screenshot = XCUIScreen.main.screenshot()
            guard let simulator = ProcessInfo().environment["SIMULATOR_DEVICE_NAME"],
                  let cacheDirectory = Snapshot.cacheDirectory else { return }
            let path = "\(cacheDirectory.path)/\(simulator)-\(name).png"
            let url = URL(fileURLWithPath: path)
            guard let data = screenshot.pngRepresentation as Data? else { return }
            do {
                try data.write(to: url)
            } catch {
                print("Problem writing screenshot: \(error)")
            }
        #endif
    }

    class func waitForLoadingIndicatorToDisappear(within timeout: TimeInterval) {
        guard let app = Snapshot.app else { return }
        let networkLoadingIndicator = app.otherElements.deviceStatusBars.networkLoadingIndicators.element
        let deadline = Date(timeIntervalSinceNow: timeout)
        while networkLoadingIndicator.exists && deadline > Date() {
            sleep(1)
        }
    }

    class func cacheDirectoryURL() throws -> URL {
        guard let simulatorHomeDir = ProcessInfo().environment["SIMULATOR_HOST_HOME"] else {
            throw SnapshotError.cannotFindSimulatorHomeDirectory
        }
        let url = URL(fileURLWithPath: simulatorHomeDir, isDirectory: true)
            .appendingPathComponent("Library/Caches/tools.fastlane")
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw SnapshotError.cannotAccessSimulatorHomeDirectory(url.path)
        }
        return url
    }
}

private extension XCUIElementAttributes {
    var isLoadingIndicator: Bool {
        let whiteListedLoaders = ["GeniusAppearance"]
        return (label == "Progress" && !whiteListedLoaders.contains(identifier))
    }
}

private extension XCUIElementQuery {
    var networkLoadingIndicators: XCUIElementQuery {
        let isNetworkLoadingIndicator = NSPredicate { (evaluatedObject, _) -> Bool in
            guard let element = evaluatedObject as? XCUIElementAttributes else { return false }
            return element.isLoadingIndicator
        }
        return self.containing(isNetworkLoadingIndicator)
    }

    var deviceStatusBars: XCUIElementQuery {
        let deviceWidth = XCUIScreen.main.coordinate(withNormalizedOffset: CGVector(dx: 1, dy: 0)).screenPoint.x
        let isStatusBar = NSPredicate { (evaluatedObject, _) -> Bool in
            guard let element = evaluatedObject as? XCUIElementAttributes else { return false }
            return element.frame.width == deviceWidth && element.frame.height <= 100
        }
        return self.containing(isStatusBar)
    }
}
